### ISSUE TITLE
ERROR in Path must be a string. Received undefined

### ISSUE THREAD

**Issue by TheoMer** [keathley/webpack-react-skeleton#17]
OS: Windows 10 Pro
NPM: 3.9.5

The above mentioned error is created after doing
1. git clone https://github.com/keathley/webpack-react-skeleton.git
2. npm install
3. npm start

See attached image:

![error in path](https://cloud.githubusercontent.com/assets/15969262/17074142/12cfcafa-5070-11e6-8208-fa9f33e16954.jpg)

**Comment by keathley** [comment]
Sorry about the issues. I've updated the packages and resolved some issues on master. If you pull it down you should be able to get things running again.

I'd also recommend that you check out https://github.com/facebookincubator/create-react-app for a really great out of the box solution. Then if you decided that you want some of the features in this skeleton you can start to pull them in and add things as you go. Thats my current strategy for new react apps.

Let me know if you have other issues.
