### ISSUE TITLE
Add jest and directory structure for tests

### ISSUE THREAD

**Issue by keathley** [keathley/webpack-react-skeleton#2]
It would be good to have all of the testing setup already done.  Going to just use Jest since that's the preferred testing framework with React.

**Comment by uzarubin** [comment]
We may or may not want to use a different test runner. Jest doesn't work with node 0.12 because of JSDOM, but it does work on the recent version of io.js. Something to consider

**Comment by keathley** [comment]
I've created an initial setup for this in #10.
